---
- name: Setup NGINX Server
  hosts: web_servers
  remote_user: user1
  become: yes

  tasks:


  - name: Basically "apt-get update" 
    apt:
      update_cache: yes

  - name: Install NGINX Packages
    apt:
      name: nginx
      state: latest

  - name: Start Service
    service:
      name: nginx
      state: restarted
      enabled: yes
