---
- name: Setup DNS BIND Server
  hosts: 192.168.3.22
  remote_user: user1
  become: yes
  vars:
      DNS_SERVER_NAME: ns1
      DNS_SERVER_IP: 192.168.3.22
      DNS_SERVER_IP_ENTRY: 22.3
      INITIAL_ZONE_NAME: lab.net
      INITIAL_ZONE_IP: 192.168
      INITIAL_ZONE_IP_R: 168.192
      NETWORK: 192.168.3

  tasks:
    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_NAME }}
        line: tiger1	IN	A	192.168.3.181
        
    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_NAME }}
        line: tiger2	IN	A	192.168.3.182

    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_NAME }}
        line: zebra1	IN	A	192.168.3.183

    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_NAME }}
        line: lion1	IN	A	192.168.3.184

    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_NAME }}
        line: lion2	IN	A	192.168.3.185

    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_IP }}
        line: 181.3	IN	PTR	tiger1.lab.net.
        
    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_IP }}
        line: 182.3	IN	PTR	tiger2.lab.net.

    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_IP }}
        line: 183.3	IN	PTR	zebra1.lab.net.

    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_IP }}
        line: 184.3	IN	PTR	lion1.lab.net.

    - name: DNS Entry
      lineinfile:
        path: /etc/bind/zones/db.{{ INITIAL_ZONE_IP }}
        line: 185.3	IN	PTR	lion2.lab.net.


    - name: Start Service
      service:
        name: bind9
        state: restarted
        enabled: yes

