---
- name: Setup DNS BIND Server
  hosts: 192.168.3.22
  remote_user: user1
  become: yes
  vars:
      DNS_SERVER_NAME: ns1
      DNS_SERVER_IP: 192.168.3.22
      DNS_SERVER_IP_ENTRY: 22.3
      INITIAL_ZONE_NAME: lab.net
      INITIAL_ZONE_IP: 192.168
      INITIAL_ZONE_IP_R: 168.192
      NETWORK: 192.168.3

  tasks:
  - name: Install DNS Packages
    apt:
      name: bind9, bind9utils, bind9-doc
      state: latest

  - name: Add a Config File
    template:
      src: /home/user1/ansible_playbooks/DNS_BIND/templates/bind9.j2
      dest: /etc/default/bind9

  - name: Add a Config File
    template:
      src: /home/user1/ansible_playbooks/DNS_BIND/templates/named.conf.options.j2
      dest: /etc/bind/named.conf.options

  - name: Add a Config File
    template:
      src: /home/user1/ansible_playbooks/DNS_BIND/templates/named.conf.local.j2
      dest: /etc/bind/named.conf.local

  - name: Use Time Since Epoc for Serial
    command: "date +%s"
    register: serial2

  - set_fact:
      serial: "{{ serial2.stdout }}"

  - name: Create Directory
    file:
      path: /etc/bind/zones
      state: directory
            
  - name: Add Forward Zone File
    template:
      src: /home/user1/ansible_playbooks/DNS_BIND/templates/db.forward_zone.j2
      dest: /etc/bind/zones/db.{{ INITIAL_ZONE_NAME }}

  - name: Add Reverse Zone File
    template:
      src: /home/user1/ansible_playbooks/DNS_BIND/templates/db.reverse_zone.j2
      dest: /etc/bind/zones/db.{{ INITIAL_ZONE_IP }}

  - name: Open Firewall for Bind9
    ufw:
      rule: allow
      name: Bind9 

#  - name: Start Service
#    service:
#      name: bind9
#      state: restarted
#      enabled: yes



