---
- name: Update web servers
  hosts: 192.168.3.22
  remote_user: user1
  become: yes

  tasks:
  - name: Install DNS Packages
    apt:
      name: bind9, bind9utils, bind9-doc
      state: latest

  - name: Add a Config File
    template:
      src: /home/user1/bind9.j2
      dest: /etc/default/bind9

  - name: Add a Config File
    template:
      src: /home/user1/named.conf.options.j2
      dest: /etc/bind/named.conf.options

  - name: Add a Config File
    template:
      src: /home/user1/named.conf.local.j2
      dest: /etc/bind/named.conf.local

  - name: Add Forward Zone File
    template:
      src: /home/user1/db.example.org.j2
      dest: /etc/bind/zones/db.example.org

  - name: Add Reverse Zone File
    template:
      src: /home/user1/db.192.168.j2
      dest: /etc/bind/zones/db.192.168

  - name: Open Firewall for Bind9
    ufw:
      rule: allow
      name: Bind9 

  - name: Start Service
    service:
      name: bind9
      state: restarted
      enabled: yes



